### ISSUE TITLE
vimrc error

### ISSUE THREAD

**Issue by yishuiliunian** [jarolrod/vim-python-ide#2]
~~~
第  109 行: E518: 未知的选项: pyxversion=0
~~~

**Comment by Braincoke** [comment]
Hi,
That is a very cryptic way of posting an issue.
I assume the problem is that you have a version of vim < [8.0.0251](https://raw.githubusercontent.com/vim/vim/master/runtime/doc/version8.txt) where the `pyxversion` option is available.
For more information about the option, see [this link](http://vimhelp.appspot.com/options.txt.html).
